import { Product } from "@/types/productType";
export const data: Product[] = [
    {
        id: '1',
        name: 'Basic Tee 6-Pack ',
        description: 'These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they’ll withstand everything the weather can offer.',
        price: '192',
        rating: 3.9,
        reviewCount: 117,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-02-detail.jpg',
        imageAlt: 'Two each of gray, white, and black shirts arranged on table.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '2',
        name: 'Nomad Tumbler',
        description: 'Keep your beverages hot or cold all day! This 20 oz stainless steel tumbler features double-wall vacuum insulation and a push-button flip lid. It comes with both a reusable plastic straw and a reusable stir stick.',
        price: '35',
        rating: 4.2,
        reviewCount: 74,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-01-detail.jpg',
        imageAlt: 'Hand holding black stainless steel tumbler with white base and black lid.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '3',
        name: 'Focus Paper Refill',
        description: 'Keep your notes organized with this refill pack of paper for your Focus notebook. Each pack contains three notebooks with 100 sheets of paper each.',
        price: '13',
        rating: 4.6,
        reviewCount: 68,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-03-detail.jpg',
        imageAlt: 'Three notebooks stacked on top of each other. One open showing lined ivory paper.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name
                : 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900'
            },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '4',
        name: 'Machined Mechanical Pencil',
        description: 'This durable machined mechanical pencil is made entirely from a single block of metal. With a removable clip for your pocket, it’s the perfect take-anywhere mechanical pencil.',
        price: '35',
        rating: 3.9,
        reviewCount: 83,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-04-detail.jpg',
        imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring-gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '5',
        name: 'Hand Painted Blue Band Mug',
        description: 'This hand-thrown porcelain mug features a hand-painted band of blue glaze.',
        price: '28',
        rating: 4.3,
        reviewCount: 52,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-05-detail.jpg',
        imageAlt: 'Hand-painted porcelain mug with imperfectly round top and blue glaze on white background.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring:gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '6',
        name: 'Hand Painted Blue Band Mug',
        description: 'This hand-thrown porcelain mug features a hand-painted band of blue glaze.',
        price: '28',
        rating: 4.3,
        reviewCount: 52,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-05-detail.jpg',
        imageAlt: 'Hand-painted porcelain mug with imperfectly round top and blue glaze on white background.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring:gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '7',
        name: 'Hand Painted Blue Band Mug',
        description: 'This hand-thrown porcelain mug features a hand-painted band of blue glaze.',
        price: '28',
        rating: 4.3,
        reviewCount: 52,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-05-detail.jpg',
        imageAlt: 'Hand-painted porcelain mug with imperfectly round top and blue glaze on white background.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring:gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '8',
        name: 'Hand Painted Blue Band Mug',
        description: 'This hand-thrown porcelain mug features a hand-painted band of blue glaze.',
        price: '28',
        rating: 4.3,
        reviewCount: 52,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-05-detail.jpg',
        imageAlt: 'Hand-painted porcelain mug with imperfectly round top and blue glaze on white background.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring:gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '9',
        name: 'Hand Painted Blue Band Mug',
        description: 'This hand-thrown porcelain mug features a hand-painted band of blue glaze.',
        price: '28',
        rating: 4.3,
        reviewCount: 52,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-05-detail.jpg',
        imageAlt: 'Hand-painted porcelain mug with imperfectly round top and blue glaze on white background.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring:gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '10',
        name: 'Hand Painted Blue Band Mug',
        description: 'This hand-thrown porcelain mug features a hand-painted band of blue glaze.',
        price: '28',
        rating: 4.3,
        reviewCount: 52,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-05-detail.jpg',
        imageAlt: 'Hand-painted porcelain mug with imperfectly round top and blue glaze on white background.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring:gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    },
    {
        id: '11',
        name: 'Hand Painted Blue Band Mug',
        description: 'This hand-thrown porcelain mug features a hand-painted band of blue glaze.',
        price: '28',
        rating: 4.3,
        reviewCount: 52,
        href: '#',
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/product-quick-preview-05-detail.jpg',
        imageAlt: 'Hand-painted porcelain mug with imperfectly round top and blue glaze on white background.',
        colors: [
            { name: 'White', class: 'bg-white', selectedClass: 'ring-gray-400' },
            { name: 'Gray', class: 'bg-gray-200', selectedClass: 'ring-gray-400' },
            { name: 'Black', class: 'bg-gray-900', selectedClass: 'ring:gray-900' },
        ],
        sizes: [
            { name: 'XXS', inStock: true },
            { name: 'XS', inStock: true },
            { name: 'S', inStock: true },
            { name: 'M', inStock: true },
            { name: 'L', inStock: true },
            { name: 'XL', inStock: true },
            { name: 'XXL', inStock: true },
            { name: 'XXXL', inStock: false },
        ],
    }

]

